[buildPlans.IosevkaCapy]
family = "Iosevka Capy"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCapy.variants.design]
one = "base"
six = "closed-contour"
nine = "closed-contour"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-q = "straight"
capital-w = "straight-vertical-sides-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
f = "flat-hook-serifless"
g = "double-storey"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
m = "serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
w = "straight-serifless"
y = "straight-turn-serifless"
lower-gamma = "straight"
lower-delta = "flat-top"
lower-pi = "tailless"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
bar = "natural-slope"
question = "corner"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCapy.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCapy.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
